services:
  db:
    image: postgres:latest
    container_name: db_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres

volumes:
  pgdata:
    driver: local
